export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST"
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL"
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET"

export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST"
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS"
export const GET_BLOG_FAIL = "GET_BLOG_FAIL"

export const GET_ALL_BLOG_REQUEST = "GET_ALL_BLOG_REQUEST"
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS"
export const GET_ALL_BLOG_FAIL = "GET_ALL_BLOG_FAIL"

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET"


export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST"
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL"
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET"


export const RECOVER_BLOG_REQUEST = "RECOVER_BLOG_REQUEST"
export const RECOVER_BLOG_SUCCESS = "RECOVER_BLOG_SUCCESS"
export const RECOVER_BLOG_FAIL = "RECOVER_BLOG_FAIL"
export const RECOVER_BLOG_RESET = "RECOVER_BLOG_RESET"

export const CLEAR_ERROR = "CLEAR_ERROR"